
title: Séries temporais
description: Departamento de Estatística - UFLA.
theme: jekyll-theme-architect
gem "github-pages", group: :jekyll_plugins

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
