
title: Séries temporais
description: Departamento de Estatística - UFLA.
theme: jekyll-theme-architect
gem "github-pages", group: :jekyll_plugins

#Others
markdown: kramdown

body {
    background-color: #cce5ff !important;
}
